// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCx63rm9oAxb3meLDQ-E9rAkNtePV3H74',
    appId: '1:464191483201:web:dfa84e6616057c686ac5c0',
    messagingSenderId: '464191483201',
    projectId: 'todo01-16e67',
    authDomain: 'todo01-16e67.firebaseapp.com',
    storageBucket: 'todo01-16e67.appspot.com',
    measurementId: 'G-E739EJGXHK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDDoqgDpYGfXxqzMgMyg82NdvZZEKEvB4',
    appId: '1:464191483201:android:4c0580a44c32421d6ac5c0',
    messagingSenderId: '464191483201',
    projectId: 'todo01-16e67',
    storageBucket: 'todo01-16e67.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEbmFJl_-_pbQBIVsIwD8S96BJM6Jfe3E',
    appId: '1:464191483201:ios:7c0ccfe1effe3fdd6ac5c0',
    messagingSenderId: '464191483201',
    projectId: 'todo01-16e67',
    storageBucket: 'todo01-16e67.appspot.com',
    iosBundleId: 'com.example.todo01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEbmFJl_-_pbQBIVsIwD8S96BJM6Jfe3E',
    appId: '1:464191483201:ios:7c0ccfe1effe3fdd6ac5c0',
    messagingSenderId: '464191483201',
    projectId: 'todo01-16e67',
    storageBucket: 'todo01-16e67.appspot.com',
    iosBundleId: 'com.example.todo01',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCx63rm9oAxb3meLDQ-E9rAkNtePV3H74',
    appId: '1:464191483201:web:5efd0513ac1e5f086ac5c0',
    messagingSenderId: '464191483201',
    projectId: 'todo01-16e67',
    authDomain: 'todo01-16e67.firebaseapp.com',
    storageBucket: 'todo01-16e67.appspot.com',
    measurementId: 'G-MF4TGEQ6ZB',
  );
}
